pipelines:
  - name: test_task
    steps:
      - name: test_task
        type: Bash
        configuration:
          integrations:
            - name: jpat
        execution:
          onExecute:
            - task: jfrog/slack-notify@latest
              id: monitor_task_pipelines
              input:
                slackIntegration: "slack_int"
                message: "Hello, World!"
